# -*- coding: utf-8 -*-
"""google ocr2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xE3gzi7xdDgV4U4iwPHgWqxvF6BthI_o
"""

import json
import re

def extract_store_names(json_file_path):
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    results = []

    for item in data:
        image_name = item.get("image_name", "Unknown")
        full_text = item.get("full_text", "")

        # 1. 텍스트를 줄바꿈 기준으로 나눔
        lines = [line.strip() for line in full_text.split('\n') if line.strip()]

        store_name = ""
        if lines:
            # 보통 첫 줄이 상호명인 경우가 많음
            first_line = lines[0]

            # 다이소처럼 "국민가게, 다이소" 같은 슬로건이 첫 줄인 경우 처리
            if "국민가게" in first_line and len(lines) > 1:
                store_name = lines[1]
            else:
                store_name = first_line

        # 2. 불필요한 노이즈 제거 (전화번호나 특수문자 등)
        store_name = re.sub(r'전화\s*:.*', '', store_name) # 전화번호 문구 제거
        store_name = store_name.strip()

        results.append({
            "image_name": image_name,
            "store_name": store_name
        })

    return results

# 파일 실행 및 결과 출력
parsed_data = extract_store_names('vision_results.json')

print(f"{'파일명':<15} | {'추출된 상호명'}")
print("-" * 40)
for entry in parsed_data:
    print(f"{entry['image_name']:<15} | {entry['store_name']}")

import json
import re

def refine_ocr_to_json(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    refined_list = []

    for entry in raw_data:
        full_text = entry.get("full_text", "")
        lines = [line.strip() for line in full_text.split('\n') if line.strip()]

        if not lines:
            continue

        # 1. 상호명 추출 로직
        # 첫 줄이 슬로건인 경우 두 번째 줄 선택, 아니면 첫 줄 선택
        store_name = lines[0]
        if "국민가게" in store_name or "emart" in store_name.lower():
            store_name = lines[1] if len(lines) > 1 else lines[0]

        # 상호명에서 (주), 주식회사 등 제거 (DB 인덱싱 최적화)
        store_name = re.sub(r'\(주\)|주식회사|^\s*["\']|["\']\s*$', '', store_name).strip()

        # 2. 사업자 번호 추출 (패턴: 000-00-00000)
        biz_num_match = re.search(r'\d{3}-\d{2}-\d{5}', full_text)
        biz_number = biz_num_match.group() if biz_num_match else None

        # 3. 전화번호 추출
        tel_match = re.search(r'(\d{2,4}-\d{3,4}-\d{4})', full_text)
        tel = tel_match.group() if tel_match else None

        # 4. JSON 구조 생성 (DB 컬럼에 맞춤)
        refined_item = {
            "image_id": entry.get("image_name"),
            "store_name": store_name,
            "biz_number": biz_number,
            "tel": tel,
            "raw_text_length": len(full_text)
        }
        refined_list.append(refined_item)

    # 결과 저장
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(refined_list, f, ensure_ascii=False, indent=4)

    return refined_list

# 실행
result = refine_ocr_to_json('vision_results.json', 'refined_data.json')
print(f"총 {len(result)}건의 데이터가 정제되었습니다.")

import json
import re

def get_refined_store_name(lines):
    if not lines:
        return "Unknown"

    # 1. 제외할 노이즈 키워드 (상호명으로 부적절한 것들)
    noise_keywords = ["영수증", "매장", "관리자", "계산원", "대표", "주소", "카드"]

    # 2. 다이소, 이마트 등 특정 브랜드 특화 로직
    full_content = " ".join(lines)
    if "다이소" in full_content: return "아성다이소"
    if "emart" in full_content.lower() or "이마트" in full_content: return "이마트"
    if "lottemart" in full_content.lower() or "롯데마트" in full_content: return "롯데마트"

    # 3. 줄별 탐색 로직
    for i, line in enumerate(lines[:5]): # 상단 5줄 이내에서 탐색
        clean_line = re.sub(r'[^\w\s\(\)]', '', line).strip() # 특수문자 제거

        # 너무 짧은 글자(예: "소", "점")는 건너뜀
        if len(clean_line) <= 1:
            continue

        # 사업자번호나 날짜가 포함된 줄은 상호명이 아님
        if re.search(r'\d{3}-\d{2}-\d{5}|\d{4}-\d{2}-\d{2}', line):
            continue

        # "국민가게", "즐거운 쇼핑" 같은 슬로건 뒤에 상호명이 오는 경우 처리
        if any(keyword in clean_line for keyword in ["국민가게", "즐거운", "어서오세요"]):
            if i + 1 < len(lines):
                return lines[i+1].strip()

        return clean_line

    return lines[0] # 최후의 수단으로 첫 줄 반환

def process_vision_data(input_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    refined_results = []
    for entry in raw_data:
        full_text = entry.get("full_text", "")
        lines = [l.strip() for l in full_text.split('\n') if l.strip()]

        # 개선된 함수 호출
        store_name = get_refined_store_name(lines)

        # 사업자번호 추출
        biz_match = re.search(r'\d{3}-\d{2}-\d{5}', full_text)

        refined_results.append({
            "image_id": entry.get("image_name"),
            "store_name": store_name,
            "biz_number": biz_match.group() if biz_match else None,
            "tel": re.search(r'\d{2,4}-\d{3,4}-\d{4}', full_text).group() if re.search(r'\d{2,4}-\d{3,4}-\d{4}', full_text) else None
        })

    return refined_results

# 결과 확인
final_data = process_vision_data('vision_results.json')
print(json.dumps(final_data[:3], ensure_ascii=False, indent=4))

import json
import re

def refine_ocr_to_db_json(json_file_path):
    with open(json_file_path, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    refined_results = []

    # 주요 브랜드 보정 맵 (OCR이 '소'라고만 해도 '다이소'로 인식하게 함)
    brand_map = {
        "다이소": "아성다이소",
        "emart": "이마트",
        "이마트": "이마트",
        "lottemart": "롯데마트",
        "롯데마트": "롯데마트",
        "한국마트": "한국마트",
        "천사마트": "천사마트",
        "1004마트": "천사마트"
    }

    for entry in raw_data:
        full_text = entry.get("full_text", "")
        lines = [line.strip() for line in full_text.split('\n') if line.strip()]

        # 1. 상호명 추출 로직 (우선순위 적용)
        store_name = "Unknown"

        # 전략 A: 텍스트 전체에서 브랜드 키워드 검색 (가장 정확)
        found_brand = False
        for keyword, official_name in brand_map.items():
            if keyword in full_text.lower():
                # 지점명까지 찾기 (예: 아성다이소_청주산남점)
                branch_match = re.search(rf'({keyword}[^\s\n]*)', full_text.replace(" ", ""))
                if branch_match:
                    store_name = branch_match.group(0)
                else:
                    store_name = official_name
                found_brand = True
                break

        # 전략 B: 브랜드 맵에 없을 경우 줄 단위 분석
        if not found_brand and lines:
            for line in lines[:3]: # 상단 3줄 탐색
                # 한 글자 노이즈("소", "가") 및 불필요 문구 제외
                if len(line) > 1 and not any(k in line for k in ["영수증", "매장", "전화"]):
                    store_name = line
                    break

        # 2. 사업자 번호 추출
        biz_match = re.search(r'\d{3}-\d{2}-\d{5}', full_text)
        biz_number = biz_match.group() if biz_match else None

        # 3. 전화번호 추출
        tel_match = re.search(r'(\d{2,4}-\d{3,4}-\d{4})', full_text)
        tel = tel_match.group() if tel_match else None

        # 최종 객체 생성
        refined_item = {
            "image_id": entry.get("image_name"),
            "store_name": store_name,
            "biz_number": biz_number,
            "tel": tel,
            "status": "success" if biz_number else "check_required"
        }
        refined_results.append(refined_item)

    return refined_results

# 실행 및 결과 확인
final_json_output = refine_ocr_to_db_json('vision_results.json')
print(json.dumps(final_json_output, ensure_ascii=False, indent=4))

import json
import re

def refine_to_final_schema(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    final_json_list = []

    # 보정용 브랜드 키워드
    brand_keywords = {
        "다이소": "아성다이소",
        "이마트": "이마트",
        "롯데마트": "롯데마트",
        "천사마트": "천사(1004)마트",
        "한국마트": "주)한국마트"
    }

    for entry in raw_data:
        full_text = entry.get("full_text", "")
        lines = [l.strip() for l in full_text.split('\n') if l.strip()]

        # 1. 상호명(store_name) 정밀 추출
        store_name = "미상"
        found = False

        # 전략 A: 브랜드 키워드 우선 검색
        for kw, official in brand_keywords.items():
            if kw in full_text.lower():
                # 지점 정보가 포함된 줄이 있다면 그걸 사용
                for line in lines:
                    if kw in line.lower() and len(line) > 2:
                        store_name = line
                        found = True
                        break
                if not found:
                    store_name = official
                    found = True
                break

        # 전략 B: 키워드가 없으면 상단 라인 분석
        if not found and lines:
            for line in lines[:3]:
                if len(line) > 1 and not any(k in line for k in ["영수증", "매장"]):
                    store_name = line
                    break

        # 2. 상호명 노이즈 제거 (예: "명 : 천사마트" -> "천사마트")
        store_name = re.sub(r'^(명|상호|상호명|가맹점명)\s*[:：]\s*', '', store_name).strip()
        store_name = store_name.replace('"', '')

        # 3. 날짜 추출 (YYYY-MM-DD)
        date_match = re.search(r'(\d{2,4})[-/.](0[1-9]|1[0-2])[-/.](0[1-9]|[12][0-9]|3[01])', full_text)
        if date_match:
            y, m, d = date_match.groups()
            year = y if len(y) == 4 else f"20{y}"
            formatted_date = f"{year}-{m}-{d}"
        else:
            formatted_date = "2024-00-00" # 기본값

        # 4. 합계 금액(total) 추출
        amounts = re.findall(r'(?:합계|계|금액|결제액)\s*[:：]?\s*([\d,]{3,})', full_text)
        if not amounts:
            amounts = re.findall(r'([\d,]{3,})', full_text)

        total_val = 0
        if amounts:
            # 가장 큰 금액 혹은 마지막 금액을 합계로 추정 (쉼표 제거 후 정수 변환)
            clean_amounts = [int(a.replace(',', '')) for a in amounts if a.replace(',', '').isdigit()]
            total_val = max(clean_amounts) if clean_amounts else 0

        # 5. 최종 구조 생성
        db_ready_item = {
            "user_id": 1,
            "image_path": entry.get("image_name"),
            "category": "기타", # 기본값 세팅
            "date": formatted_date,
            "total": total_val,
            "store_name": store_name,
            "payment": "card", # 대부분 카드 영수증이므로 기본값
            "details": {
                "items": [],
                "tax": "",
                "discount": 0,
                "card_number": "",
                "address": "",
                "tel": ""
            }
        }
        final_json_list.append(db_ready_item)

    # 파일 저장
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(final_json_list, f, ensure_ascii=False, indent=2)

    return final_json_list

# 실행
output = refine_to_final_schema('vision_results.json', 'db_import.json')
print(f"총 {len(output)}건의 데이터가 db_import.json으로 추출되었습니다.")

import json
import re

def refine_receipt_data(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    final_json_list = []

    for entry in raw_data:
        full_text = entry.get("full_text", "")
        lines = [l.strip() for l in full_text.split('\n') if l.strip()]

        # 1. 상호명(store_name) 정밀 추출 로직
        # '몰', '점', '마트', '식품' 등 상호명 키워드 우선순위 배치
        store_name = "미상"
        priority_keywords = ["점", "몰", "마트", "식품", "다이소", "이마트", "식당"]

        # 상단 10줄 이내에서 핵심 키워드가 있는 줄을 먼저 찾음
        found = False
        for line in lines[:10]:
            # [영수증], [매장] 같은 시스템 문구는 제외
            if any(k in line for k in priority_keywords) and "[" not in line and "전화" not in line:
                # "명 : " 같은 접두사 제거
                store_name = re.sub(r'^(명|상호|상호명|가맹점명)\s*[:：]\s*', '', line).strip()
                found = True
                break

        # 키워드 매칭 실패 시 두 번째 줄 선택 (첫 줄은 보통 [영수증]인 경우가 많음)
        if not found and len(lines) > 1:
            store_name = lines[1] if "[" in lines[0] else lines[0]

        # 2. 합계 금액(total) 정밀 추출 로직 (통계 파괴 방지)
        # 10억 이상의 숫자는 거래번호일 확률이 높으므로 필터링 (일반 영수증 기준)
        total_val = 0

        # '합계', '계', '결제액' 뒤에 오는 숫자 탐색
        amount_patterns = re.findall(r'(?:합계|계|결제액|받을금액)\s*[:：]?\s*([\d,]{3,})', full_text)

        if amount_patterns:
            # 쉼표 제거 후 숫자로 변환, 비정상적으로 큰 숫자(거래번호 등) 제외
            candidate_amounts = [int(a.replace(',', '')) for a in amount_patterns if a.replace(',', '').isdigit()]
            valid_amounts = [a for a in candidate_amounts if a < 10000000] # 1,000만원 이하만 합계로 인정
            if valid_amounts:
                total_val = valid_amounts[-1] # 보통 마지막에 찍히는 게 최종 합계

        # 3. 날짜 추출 (YYYY-MM-DD)
        date_match = re.search(r'(\d{2,4})[-/.](0[1-9]|1[0-2])[-/.](0[1-9]|[12][0-9]|3[01])', full_text)
        formatted_date = f"{date_match.group(1) if len(date_match.group(1))==4 else '20'+date_match.group(1)}-{date_match.group(2)}-{date_match.group(3)}" if date_match else "2024-00-00"

        # 최종 스키마 구조
        db_ready_item = {
            "user_id": 1,
            "image_path": entry.get("image_name"),
            "category": "기타",
            "date": formatted_date,
            "total": total_val,
            "store_name": store_name,
            "payment": "card",
            "details": {
                "items": [],
                "tax": "",
                "discount": 0,
                "card_number": "",
                "address": "",
                "tel": ""
            }
        }
        final_json_list.append(db_ready_item)

    # JSON 파일 생성
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(final_json_list, f, ensure_ascii=False, indent=2)

    return f"{output_file} 생성 완료"

# 실행
refine_receipt_data('vision_results.json', 'db_import_fixed.json')

import json
import re

def get_refined_json(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    final_list = []

    for entry in raw_data:
        full_text = entry.get("full_text", "")
        lines = [l.strip() for l in full_text.split('\n') if l.strip()]

        # 1. 상호명(store_name) 추출: '점', '몰', '마트' 우선 탐색 및 노이즈 제거
        store_name = "미상"
        keywords = ["점", "몰", "마트", "식품", "다이소", "이마트", "롯데", "본점"]

        found_store = False
        for line in lines[:8]:  # 상단 8줄 탐색
            if any(k in line for k in keywords) and not any(x in line for x in ["[", "번호", "대표"]):
                store_name = re.sub(r'^(명|상호|상호명|가맹점명)\s*[:：]\s*', '', line).strip()
                found_store = True
                break
        if not found_store and lines:
            store_name = lines[1] if "[" in lines[0] and len(lines) > 1 else lines[0]

        # 2. 합계 금액(total) 추출 로직 강화
        total_val = 0

        # 숫자 후보군 추출 (점/쉼표 포함된 숫자들)
        # 231229... 같은 긴 번호 제외를 위해 3~10자리 숫자만 타겟팅
        all_numbers = re.findall(r'[\d,\.]{3,10}', full_text)
        clean_numbers = []
        for n in all_numbers:
            # 점(.)이나 쉼표(,) 제거 후 숫자로 변환
            num_str = n.replace(',', '').replace('.', '')
            if num_str.isdigit():
                clean_numbers.append(int(num_str))

        # 전략 A: 특정 키워드(합계, 계, 카드, 현금) 근처의 숫자 찾기
        target_match = re.search(r'(?:합계|계|금액|결제|현금|카드|승인금액)\s*[:：]?\s*([\d,\.]{3,12})', full_text)
        if target_match:
            total_val = int(target_match.group(1).replace(',', '').replace('.', ''))

        # 전략 B: 키워드로 못 찾았을 때, 추출된 숫자 중 '가장 큰 값' (단, 바코드급 숫자는 제외)
        elif clean_numbers:
            # 보통 1,000,000원 이하의 금액 중 가장 큰 값을 합계로 추정
            candidates = [n for n in clean_numbers if 100 < n < 1000000]
            if candidates:
                total_val = max(candidates)

        # 3. 날짜 추출
        date_match = re.search(r'(\d{2,4})[-/.](0[1-9]|1[0-2])[-/.](0[1-9]|[12][0-9]|3[01])', full_text)
        date_str = "2024-01-01"
        if date_match:
            y, m, d = date_match.groups()
            year = y if len(y) == 4 else f"20{y}"
            date_str = f"{year}-{m}-{d}"

        # 스키마 구성
        item = {
            "user_id": 1,
            "image_path": entry.get("image_name"),
            "category": "기타",
            "date": date_str,
            "total": total_val,
            "store_name": store_name,
            "payment": "card",
            "details": {
                "items": [], "tax": "", "discount": 0, "card_number": "", "address": "", "tel": ""
            }
        }
        final_list.append(item)

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(final_list, f, ensure_ascii=False, indent=2)

    return f"파일 생성 완료: {output_file}"

# 실행
get_refined_json('vision_results.json', 'db_final_import.json')