ITEM_CATEGORY_RULES = {
    "식비": ["우삼겹", "돈까스", "국수", "샌드위치", "라떼", "커피", "스프", "샐러드",
           "김밥", "국밥", "치킨", "피자", "버거", "쌀국수", "포케", "도시락", "뷔페", "회식", "배달", "포장",
           "요기요", "배달의민족", "쿠팡이츠", "배달통", "위메프오", "카카오톡주문하기", "네이버페이주문하기",
           "떡볶이", "순대", "오뎅", "튀김", "족발", "보쌈", "삼겹살", "갈비", "곱창", "막창", "양념치킨",
           "후라이드치킨", "간장치킨", "파닭", "핫도그", "떡강정", "치즈볼", "피자", "페퍼로니", "콤비네이션",
           "불고기", "새우버거", "치즈버거", "국밥", "칼국수", "비빔밥", "김치찌개", "된장찌개", "순두부찌개", 
           "갈비탕", "설렁탕", "삼계탕", "냉면", "쫄면", "우동", "라멘", "샌드위치", "햄버거", "스테이크", "파스타", 
           "리조또", "카레", "라떼", "아메리카노", "카푸치노", "콜드브루", "주스", "케잌", "빵", "회", "초밥", "롤", "사시미",
           "아메리카노", "카푸치노", "콜드브루", "주스", "케잌", "빵", "타코", "브리또", "샤와르마", "케밥", "훠궈", "딤섬",
           "만두", "월남쌈", "분짜", "반미", "볶음", "튀김", "조림", "구이", "찜", "조개구이", "회덮밥", "낙지볶음", "오징어볶음", 
           "닭갈비", "라멘", "라멘", "카츠", "덮밥", "가츠동", "오야코동", "텐동", "우동", "소바", "냉우동", "비빔우동", "쫄면", 
           "냉면", "비빔냉면", "물냉면", "회냉면", "나시고랭", "미고랭", "꼬치", "사테", "렌당", "비리야니", "푸팟퐁커리", "똠양꿍",
           "짜장면", "짬뽕", "탕수육", "양장피", "팔보채", "깐풍기", "마라탕", "마라샹궈", "훠궈", "딤섬", "만두", "조기탕",
           "매운탕", "해장국", "김치", "된장국", "찌개", "오므라이스", "제육볶음", "우삼겹", "튜나", "참치"],
    "카페": ["아메리카노", "카페라떼", "카푸치노", "콜드브루", "에스프레소", "모카", "마끼아또", "프라푸치노", "주스", "스무디", "밀크티",
           "americano", "cafe latte", "cappuccino", "cold brew", "espresso", "mocha", "macchiato", "frappuccino", "juice", "smoothie", "milktea"
           "Americano", "Cafe Latte", "Cappuccino", "Cold Brew", "Espresso", "Mocha", "Macchiato", "Frappuccino", "Juice", "Smoothie", "MilkTea"],
    "쇼핑": ["티셔츠", "바지", "가방", "화장품", "스니커즈", "전자제품", "휴대폰", "노트북", "헤드폰", "액세서리", "시계", "주얼리", "인형", "완구", "책",
           "가구", "인테리어", "생활용품", "주방용품", "침구", "수납", "조명", "가전제품", "컴퓨터", "모니터", "프린터", "카메라", "TV",
           "책상", "의자", "소파", "침대", "옷장", "신발장", "식탁", "화장대", "TV장", "선반", "커텐", "shirt", "pants", "bag", "cosmetic", "sneakers", "electronics", "phone", "laptop", "headphones", "accessory", "watch", "jewelry", "doll", "toy", "book",
           "furniture", "interior", "household", "kitchenware", "bedding", "storage", "lighting", "appliance", "computer", "monitor", "printer", "camera", "TV",
           "desk", "chair", "sofa", "bed", "wardrobe", "shoe_rack", "dining_table", "vanity", "TV_stand", "shelf",
           "onepiece", "dress", "skirt", "blouse", "jacket", "coat", "sweater", "hoodie", "jeans", "shorts", "socks",
           "shirt", "pants", "bag", "cosmetic", "sneakers", "electronics", "phone", "laptop", "headphones", "accessory", "watch", "jewelry", "doll", "toy", "book",
           "furniture", "interior", "household", "kitchenware", "bedding", "storage", "lighting", "appliance", "computer", "monitor", "printer", "camera", "TV",
           "desk", "chair", "sofa", "bed", "wardrobe", "shoe_rack", "dining_table", "vanity", "TV_stand", "shelf",
           "onepiece", "dress", "skirt", "blouse", "jacket", "coat", "sweater", "hoodie", "jeans", "shorts", "socks"],
    "의료": ["약국", "병원", "치과", "한의원", "의원", "클리닉", "테라피", "피부과", "안과", "이비인후과", "응급",
           "약", "의약품", "처방전", "진료", "검사", "수술", "치료", "보건", "건강", "의료", "의사", "간호", "약사", 
           "피부", "성형", "미용", "안경", "렌즈", "레이저", "마사지", "스파", "찜질", "한약", "영양제", "건강식품",
           "비타민", "프로폴리스", "오메가3", "유산균", "감기약", "소화제", "진통제", "해열제", "알약", "연고", "패치",
           "충치", "임플란트", "교정", "스케일링", "뿌리", "신경치료", "발치", "보철", "피부과", "레이저"
           ]
    }