# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18npJ2wEwq5lkphtLXoROAtIS2H2vyPMC

다음은 한 사용자의 월 소비 데이터입니다.

1. 소비 비율 분석
2. 과소비 항목 판단
3. 절약 가능 항목 제안
4. 구체적인 행동 조언
5. 한 줄 요약

데이터:
{JSON 데이터 붙여넣기}"
"""

import json

ai_test_data = {
  "user_id": 1,
  "monthly_income": 2800000,
  "analysis_period": "2024-01 ~ 2024-03",
  "monthly_data": [
    {
      "month": "2024-01",
      "total_expense": 1900000,
      "savings": 900000,
      "category_breakdown": {
        "식비": 500000,
        "카페": 120000,
        "쇼핑": 300000,
        "교통": 100000,
        "게임": 80000,
        "기타": 800000
      }
    },
    {
      "month": "2024-02",
      "total_expense": 2200000,
      "savings": 600000,
      "category_breakdown": {
        "식비": 650000,
        "카페": 180000,
        "쇼핑": 400000,
        "교통": 120000,
        "게임": 150000,
        "기타": 700000
      }
    },
    {
      "month": "2024-03",
      "total_expense": 2500000,
      "savings": 300000,
      "category_breakdown": {
        "식비": 800000,
        "카페": 250000,
        "쇼핑": 350000,
        "교통": 130000,
        "게임": 300000,
        "기타": 670000
      }
    }
  ]
}

with open("ai_spending_analysis_test.json", "w", encoding="utf-8") as f:
    json.dump(ai_test_data, f, ensure_ascii=False, indent=2)

print("ai_spending_analysis_test.json 저장 완료 ✅")